# This is a basic workflow to help you get started with Actions
name: Build and Deploy to Netlify

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: 'CheckOut Sourse Code'

      - name: Setup Node.js Env
        uses: actions/setup-node@v1.4.2
        with:
          node-version: '14.x'

      # Runs a yarn commands
      - name: Build Site
        run: yarn install --production
          yarn build

      # Netlify Actions
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.1.11
        with:
          publish-dir: './publich'
          production-branch: main
          deploy-message: '${{ github.event.head_commit.message }}'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
